<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BillingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('billings')->delete();
        
        \DB::table('billings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'reference' => 'AEC-01',
                'transID' => NULL,
                'group_id' => NULL,
                'group_role' => 'child',
                'original_payment' => 'AEC-01',
                'student' => '1',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => -949100,
                'course_id' => 3,
                'amount' => 1000000,
                'description' => 'Update',
                'due' => '2022-05-25 18:06:13',
                'title' => 'Computer Technology',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-25 15:06:13',
                'updated_at' => '2022-05-25 15:06:13',
            ),
            1 => 
            array (
                'id' => 2,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 197200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:49:19',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:49:19',
                'updated_at' => '2022-05-31 07:49:19',
            ),
            2 => 
            array (
                'id' => 3,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 196200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:51:26',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:51:26',
                'updated_at' => '2022-05-31 07:51:26',
            ),
            3 => 
            array (
                'id' => 4,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 195200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:51:52',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:51:52',
                'updated_at' => '2022-05-31 07:51:52',
            ),
            4 => 
            array (
                'id' => 5,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 194200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:52:10',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:52:10',
                'updated_at' => '2022-05-31 07:52:10',
            ),
            5 => 
            array (
                'id' => 6,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 193200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:53:03',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:53:03',
                'updated_at' => '2022-05-31 07:53:03',
            ),
            6 => 
            array (
                'id' => 7,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 192200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:53:17',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:53:17',
                'updated_at' => '2022-05-31 07:53:17',
            ),
            7 => 
            array (
                'id' => 8,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 191200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:53:41',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:53:41',
                'updated_at' => '2022-05-31 07:53:41',
            ),
            8 => 
            array (
                'id' => 9,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 190200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:55:21',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:55:21',
                'updated_at' => '2022-05-31 07:55:21',
            ),
            9 => 
            array (
                'id' => 10,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 189200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:55:36',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:55:36',
                'updated_at' => '2022-05-31 07:55:36',
            ),
            10 => 
            array (
                'id' => 11,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 188200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:55:56',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:55:56',
                'updated_at' => '2022-05-31 07:55:56',
            ),
            11 => 
            array (
                'id' => 12,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 187200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:57:02',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:57:02',
                'updated_at' => '2022-05-31 07:57:02',
            ),
            12 => 
            array (
                'id' => 13,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 186200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:57:12',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:57:12',
                'updated_at' => '2022-05-31 07:57:12',
            ),
            13 => 
            array (
                'id' => 14,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => NULL,
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 185200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 11:12:50',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 08:12:50',
                'updated_at' => '2022-05-31 08:12:50',
            ),
            14 => 
            array (
                'id' => 1,
                'reference' => 'AEC-01',
                'transID' => NULL,
                'group_id' => NULL,
                'group_role' => 'child',
                'original_payment' => 'AEC-01',
                'student' => '1',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => -949100,
                'course_id' => 3,
                'amount' => 1000000,
                'description' => 'Update',
                'due' => '2022-05-25 18:06:13',
                'title' => 'Computer Technology',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-25 15:06:13',
                'updated_at' => '2022-05-25 15:06:13',
            ),
            15 => 
            array (
                'id' => 2,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 197200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:49:19',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:49:19',
                'updated_at' => '2022-05-31 07:49:19',
            ),
            16 => 
            array (
                'id' => 3,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 196200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:51:26',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:51:26',
                'updated_at' => '2022-05-31 07:51:26',
            ),
            17 => 
            array (
                'id' => 4,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 195200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:51:52',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:51:52',
                'updated_at' => '2022-05-31 07:51:52',
            ),
            18 => 
            array (
                'id' => 5,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 194200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:52:10',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:52:10',
                'updated_at' => '2022-05-31 07:52:10',
            ),
            19 => 
            array (
                'id' => 6,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 193200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:53:03',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:53:03',
                'updated_at' => '2022-05-31 07:53:03',
            ),
            20 => 
            array (
                'id' => 7,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 192200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:53:17',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:53:17',
                'updated_at' => '2022-05-31 07:53:17',
            ),
            21 => 
            array (
                'id' => 8,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 191200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:53:41',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:53:41',
                'updated_at' => '2022-05-31 07:53:41',
            ),
            22 => 
            array (
                'id' => 9,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 190200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:55:21',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:55:21',
                'updated_at' => '2022-05-31 07:55:21',
            ),
            23 => 
            array (
                'id' => 10,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 189200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:55:36',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:55:36',
                'updated_at' => '2022-05-31 07:55:36',
            ),
            24 => 
            array (
                'id' => 11,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 188200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:55:56',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:55:56',
                'updated_at' => '2022-05-31 07:55:56',
            ),
            25 => 
            array (
                'id' => 12,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 187200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:57:02',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:57:02',
                'updated_at' => '2022-05-31 07:57:02',
            ),
            26 => 
            array (
                'id' => 13,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => 'AEC-02',
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 186200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 10:57:12',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 07:57:12',
                'updated_at' => '2022-05-31 07:57:12',
            ),
            27 => 
            array (
                'id' => 14,
                'reference' => 'AEC-02',
                'transID' => NULL,
                'group_id' => NULL,
                'group_role' => 'child',
                'original_payment' => 'AEC-02',
                'student' => '2',
                'note' => 'Thank you for choosing Atlas Educational Center',
                'balance' => 185200,
                'course_id' => 5,
                'amount' => 1000,
                'description' => 'Updated',
                'due' => '2022-05-31 11:12:50',
                'title' => 'Mechatronic Engineering',
                'paid' => 'Partially Paid',
                'created_at' => '2022-05-31 08:12:50',
                'updated_at' => '2022-05-31 08:12:50',
            ),
        ));
        
        
    }
}